Feature forms
santiagorodriguezbermudez/rails_form_app pull request #1
Opened 2020-07-14 20:57 UTC by mikethreels

# Milestone 1: Created the Reformer.

## In this milestone we accomplished:

- [x] implemented the User model, controller, and view including validations in the model
- [x] Implemented plain HTML form, updating it to a form_tag which was later updated to for_form
- [x] added the methods for creating and updating users
- [x] Implemented the error display in the browser.

2020-07-15 07:34 UTC, mosesogwo requested changes
**Hello! Great job :clap: Something is still missing in the project**

:point_right: I can't find your commented out forms - the ones created with **html form element** and **form_tag helpers**

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png)

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png)


_**Please include them and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-07-15 07:34 UTC, mosesogwo commented on app/controllers/users_controller.rb
> +      render new_user_path
`render :new` is more appropriate here
You can read about their difference [here](https://medium.com/@kerenlerner/render-and-redirect-which-to-use-106ff653ee9a)

2020-07-15 16:46 UTC, santiagorodriguezbermudez commented
# Changes # 1

## On this update we change the following:

- [x] Added the html as a comment code to the new and edit views.
- [x] Added the form_tag helper form as a comment code to the new and edit views. 
- [x] Used the :new method for the controller as suggested per the TSE

2020-07-16 06:35 UTC, uche-inyama approved these changes
## Approved

Hi team :wave: 

this project is approved, go on with the next project. :100: 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-07-16 16:01 UTC, merged